# Generated by Django 3.2.6 on 2021-08-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPatient', models.PositiveIntegerField()),
                ('accessionNumber', models.PositiveIntegerField()),
                ('domain', models.CharField(max_length=3)),
                ('dicomPath', models.CharField(max_length=70)),
                ('studyUid', models.CharField(max_length=60)),
                ('serieUid', models.CharField(max_length=60)),
                ('sopInstanceUid', models.CharField(max_length=60)),
            ],
        ),
    ]
